config/routes.rb
Rails.application.routes.draw do
  resources :form_submissions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "form_submissions#new"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/form_submission.rb
class FormSubmission < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/form_submissions_controller.rb
require 'rubygems'
gem 'pdfkit', '>= 0.8.4'
require 'pdfkit'
class FormSubmissionsController < ApplicationController
  before_action :set_form_submission, only: %i[ show edit update destroy ]
  # GET /form_submissions/1 or /form_submissions/1.json
  def show
  end

  # GET /form_submissions/new
  def new
    @form_submission = FormSubmission.new
  end

  # GET /form_submissions/1/edi
  # POST /form_submissions or /form_submissions.json
  def create
    @form_submission = FormSubmission.new(form_submission_params)

    if @form_submission.save
      generate_pdf_document(@form_submission)
      redirect_to @form_submission, notice: 'Form submission was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /form_submissions/1 or /form_submissions/1.json

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_form_submission
    @form_submission = FormSubmission.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def form_submission_params
    params.require(:form_submission).permit(
      :name,
      :country_of_origin,
      :languages,
      :location,
      :sylum_procedure_stage,
      :legal_request,
      :family_members_in_greece,
      :urgent,
      :detention
    )
  end


  def generate_pdf_document(form_submission)
    content = <<~HTML
      <h1>Hotline Form </h1>
      <p>name: #{form_submission.name}</p>
      <p>Contry of origin: #{form_submission.country_of_origin}</p>
      <p>Languages: #{form_submission.languages}</p>
      <p>Location: #{form_submission.location}</p>
      <p>Asylum Procedure Stage: #{form_submission.asylum_procedure_stage}</p>
      <p>Legal Request: #{form_submission.legal_request}</p>
      <p>Family in Greece: #{form_submission.family_members_in_greece}</p>
      <p>Urgent: #{form_submission.urgent}</p>
      <p>Detention: #{form_submission.detention}</p>

    HTML

    pdfkit = PDFKit.new(content)
    file_path = "/Users/angelosathanasiosmakris/Desktop/#{form_submission.name}.pdf" # Replace with the desired absolute file path
    pdfkit.to_file(file_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_submissions_helper.rb
module FormSubmissionsHelper
end

app/views/form_submissions/_form.html.erb
<%= form_with(model: form_submission) do |form| %>
  <% if form_submission.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(form_submission.errors.count, "error") %> prohibited this form_submission from being saved:</h2>

      <ul>
        <% form_submission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_area :message %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/form_submissions/_form_submission.html.erb
<div id="<%= dom_id form_submission %>">
  <p>
    <strong>Name:</strong>
    <%= form_submission.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= form_submission.email %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= form_submission.message %>
  </p>

</div>

app/views/form_submissions/edit.html.erb
<h1>Editing form submission</h1>

<%= render "form", form_submission: @form_submission %>

<br>

<div>
  <%= link_to "Show this form submission", @form_submission %> |
  <%= link_to "Back to form submissions", form_submissions_path %>
</div>

app/views/form_submissions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Form submissions</h1>

<div id="form_submissions">
  <% @form_submissions.each do |form_submission| %>
    <%= render form_submission %>
    <p>
      <%= link_to "Show this form submission", form_submission %>
    </p>
  <% end %>
</div>

<%= link_to "New form submission", new_form_submission_path %>

app/views/form_submissions/new.html.erb
<div class="container card shadow col-6 mt-2 pb-2">
  <h1>Legal Help Form:</h1>
  <%= simple_form_for @form_submission do |f| %>
    <%= f.input :name ,as: :string%>

    <%= f.input :country_of_origin ,as: :string%>

    <%= f.input :languages, as: :string %>

    <%= f.input :location, as: :select, collection: ['Camp', 'Self-accommodated'] %>

    <%= f.input :asylum_procedure_stage, as: :select, collection: ['Registration', 'Upcoming IV appointment', 'First decision pending', 'Second decision pending', 'Third decision pending', 'Notified subsequent application', 'Refugee status'] %>

    <%= f.input :legal_request, as: :select, collection: ['Interview preparation', 'Appeal', 'Family reunification'] %>

    <%= f.input :family_members_in_Greece, as: :boolean %>

    <%= f.input :urgent, as: :boolean, label: "Urgent?"%>
    <div class="ms-3">
      <p>Urgent cases are considered the following:</p>
      <p>• Upcoming interview appointment in <strong>less than a week</strong>.</p>
      <p>• Deadline for appeal <strong>less than 2 weeks</strong>.</p>
      <p>• Detention (*Please note that our organisation can assist only in particular cases of detention after the <strong>notification of the second / third rejection</strong>).</p>
    </div>
    <%= f.input :detention, as: :boolean %>

    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/form_submissions/show.html.erb
<div class="container card">
  <p>
    <strong>Thank you <%= @form_submission.name %>!</strong>
    It usually takes us arround 2 days to answer the forms 😊
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormToWordApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>